### ISSUE TITLE
[IMP] fieldservice: multi-company

### ISSUE THREAD

**Issue by max3903** [OCA/field-service#162]
# Todo

- [x] Add a many2one field "Company" (company_id) to:
  - [x] fsm.order
  - [x] fsm.vehicle
  - [x] fsm.equipment
  - [x] fsm.stage
  - [x] fsm.team
  - [x] territory
  - [x] branch
  - [x] district
  - [x] region

- [x] Add the field to the form views and display it only to the multi-company group
- [x] The field defaults to the company of the logged in user.
- [x] Add global record rules for the following objects to allow users to only read the records of their company and its children:

  - [x] fsm.order: `['|',('company_id','=',False),('company_id','child_of',[user.company_id.id])]`
  - [x] fsm.vehicle: `['|',('company_id','=',False),('company_id','child_of',[user.company_id.id])]`
  - [x] fsm.equipment: `['|',('company_id','=',False),('company_id','child_of',[user.company_id.id])]`
  - [x] fsm.location: `['|',('partner_id.company_id','=',False),('partner_id.company_id','child_of',[user.company_id.id])]`
  - [x] fsm.person: `['|',('partner_id.company_id','=',False),('partner_id.company_id','child_of',[user.company_id.id])]`
  - [x] fsm.stage: `['|',('company_id','=',False),('company_id','child_of',[user.company_id.id])]`
  - [x] fsm.team: `['|',('company_id','=',False),('company_id','child_of',[user.company_id.id])]`
  - [x] territory: `['|',('company_id','=',False),('company_id','child_of',[user.company_id.id])]`
  - [x] branch: `['|',('company_id','=',False),('company_id','child_of',[user.company_id.id])]`
  - [x] district: `['|',('company_id','=',False),('company_id','child_of',[user.company_id.id])]`
  - [x] region: `['|',('company_id','=',False),('company_id','child_of',[user.company_id.id])]`
