### ISSUE TITLE
[RFC] Changes on fsm (recurring) template

### ISSUE THREAD

**Issue by hparfr** [OCA/field-service#735]
I suggest some changes in v14 at least:

* fsm.template

- [ ] rename model fsm.template to fsm.order.template
- [x]  `company_id`:  remove default value (#740)
- [x] `hour` : rename field to `duration` (#740)

* fsm.recurring.template

- [x]  `company_id`:  remove default value (#865)
- [x] `frequency_set_id`: change required to False (#865)
- [x] `fsm_order_template_id` :  ~remove it~ [edit]make it optional [/edit] (see product.template) (#865)

* product.template:

- [x] `fsm_order_template_id`: required=False (xml) and invisible if tracking_policy = no (#827)
- [x] `fsm_recurring_template_id`: required=False (xml)

* fsm.recurring:
- [x] `frequency_set_id`: change required to False (#865)

Why ?
- Multicompany:  in order to be aligned with product.template, sale.order.template.
- Optional fields: In my use case, I need to set frequencies and duration in the sale_order_lines (a new module soon) 
- Having both templates on products: simpler design.
- Optional templates on products: because there is no need of mandatory templates

What do you think of it ?

**Comment by hparfr** [comment]
ping @brian10048 @max3903 @osi-scampbell

**Comment by brian10048** [comment]
I only have one objection which is in relation to removing fsm_order_template_id from fsm.recurring.template

> 
>     * fsm.template
>  
>     * [ ]  rename model fsm.template to fsm.order.template
>     * [ ]   `company_id`:  remove default value 
>     * [ ]  `hour` : rename field to `duration`

These changes to fsm.template sound good to me

> 
>     * fsm.recurring.template
> 
> 
>     * [ ]   `company_id`:  remove default value
>     * [ ]  `frequency_set_id`: change required to False
>     * [ ]  `fsm_order_template_id` : remove it (see product.template)


First 2 changes are acceptable for me

I don't agree to remove fsm_order_template_id since not all uses of the recurring template come from a product or a sale.  For us, we may create a recurring order manually that may not be related to a product at all.  We still need the fsm_order_template_id field so that each order from the recurring order is assigned a fsm order template.


> 
>     * product.template:
>     * [ ]  `fsm_order_template_id`: required=False (xml) and invisible if tracking_policy = no
>     * [ ]  `fsm_recurring_template_id`: required=False (xml)
> 

Acceptable

> 
>     * fsm.recurring:
> 
>     * [ ]  `frequency_set_id`: change required to False
> 
Acceptable

**Comment by hparfr** [comment]
> I don't agree to remove fsm_order_template_id since not all uses of the recurring template come from a product or a sale. For us, we may create a recurring order manually that may not be related to a product at all. We still need the fsm_order_template_id field so that each order from the recurring order is assigned a fsm order template.


So I suggest then to not remove it, but make it optional.

![Screenshot_2021-03-09 New - Odoo](https://user-images.githubusercontent.com/8331206/110448990-03c22d00-80c2-11eb-9c07-d1db3742b426.png)
![Screenshot_2021-03-09 New - Odoo(1)](https://user-images.githubusercontent.com/8331206/110448992-04f35a00-80c2-11eb-8b5a-ef5bc2215231.png)
![Screenshot_2021-03-09 New - Odoo(2)](https://user-images.githubusercontent.com/8331206/110448999-06248700-80c2-11eb-9884-0ab300964fe5.png)

**Comment by hparfr** [comment]
> rename model fsm.template to fsm.order.template

Still to do, but low priority for me now.
