### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/field-service#963]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] base_territory by @max3903 in #966
- [x] fieldservice by @max3903 in #967
- [x] fieldservice_account - By @gbrito-erpopen - #985
- [x] fieldservice_account_analytic - By @juliette-blanc - #1084 & @michelerusti #1127 
- [x] fieldservice_account_payment - By @rrebollo - #1489
- [x] fieldservice_activity - By @gbrito-erpopen - #982
- [ ] fieldservice_agreement #1130 
- [x] fieldservice_calendar - By @juliette-blanc - #1074
- [ ] fieldservice_change_management - By @aiendry-aktivsoftware - #1099
- [x] fieldservice_crm - By @gbrito-erpopen - #983
- [ ] fieldservice_delivery
- [ ] fieldservice_distribution
- [x] fieldservice_equipment_stock - By @szekawong - #1129
- [x] fieldservice_fleet - By @rrebollo - #1491
- [x] fieldservice_geoengine - By @peluko00 - #1169
- [ ] fieldservice_google_map
- [ ] fieldservice_google_marker_icon_picker
- [x] fieldservice_isp_account #1126 
- [x] fieldservice_isp_flow - By @peluko00 - #1168
- [ ] fieldservice_location_builder
- [ ] fieldservice_maintenance - By @jasperjumelet - #1056
- [ ] fieldservice_partner_multi_relation
- [x] fieldservice_portal - By @anusriNPS - #1224
- [x] fieldservice_project by @epanisset #1045 
- [ ] fieldservice_purchase
- [x] fieldservice_recurring - By @kaynnan - #1105
- [ ] fieldservice_repair
- [x] fieldservice_route - By @gbrito-erpopen - #992
- [ ] fieldservice_route_account
- [ ] fieldservice_route_stock
- [ ] fieldservice_route_vehicle
- [x] fieldservice_sale - By @stefan-tecnativa - #1101
- [x] fieldservice_sale_recurring - #1149 
- [ ] fieldservice_sale_stock
- [x] fieldservice_size - By @kaynnan - #1106
- [x] fieldservice_skill - By @stefan-tecnativa - #1094
- [ ] fieldservice_stage_server_action
- [x] fieldservice_stage_validation - By @juliette-blanc - #1082
- [x] fieldservice_stock - By @gbrito-erpopen - #993
- [ ] fieldservice_stock_account
- [ ] fieldservice_stock_account_analytic
- [ ] fieldservice_stock_request - By @peluko00 
- [ ] fieldservice_substatus - By @gbrito-erpopen - #990
- [x] fieldservice_timeline - By @houzefa-abba - #1171
- [ ] fieldservice_vehicle
- [ ] fieldservice_vehicle_stock
- [ ] fieldservice_vehicle_stock_request
- [ ] fieldservice_web_timeline_view

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by michelerusti** [comment]
migrating: 
- [x] **fieldservice_isp_account**: #1126 
- [x] **fieldservice_account_analytic**: #1127

**Comment by peluko00** [comment]
migrating: 
- [fieldservice_stock_request] https://github.com/OCA/field-service/pull/1172 
- [fieldservice_geoengine] https://github.com/OCA/field-service/pull/1169
- [fieldservice_isp_flow] https://github.com/OCA/field-service/pull/1168

**Comment by houzefa-abba** [comment]
fieldservice_timeline: https://github.com/OCA/field-service/pull/1171

**Comment by 99BenJ99** [comment]
Hello,

Can we try your application?


Benjamin Hagenbuch
004179 260 80 88


________________________________
De : Antoni Marroig Campomar ***@***.***>
Envoyé : mercredi 3 avril 2024 13:23
À : OCA/field-service ***@***.***>
Cc : Benjamin Hagenbuch ***@***.***>; Manual ***@***.***>
Objet : Re: [OCA/field-service] Migration to version 16.0 (Issue #963)


migrating:
fieldservice_stock_request
fieldservice_geoengine
fieldservice_isp_flow

**Comment by max3903** [comment]
> Benjamin Hagenbuch

My colleague @dreispt will contact you.

**Comment by max3903** [comment]
> Hello, Can we try your application? Benjamin Hagenbuch 004179 260 80 88

My colleague @dreispt will contact you.

**Comment by aaladro-kernet** [comment]
fieldservice_repair: https://github.com/OCA/field-service/pull/1288
